[build]
  base = "frontend"
  publish = "dist"
  command = """
    cd ../.netlify/functions && npm install && cd ../../frontend && \
    yarn install --frozen-lockfile && \
    yarn add -D autoprefixer@10.4.14 postcss@8.4.23 tailwindcss@3.3.2 @vitejs/plugin-react@4.0.0 vite@4.3.5 && \
    CI=false yarn build
  """
  functions = "../.netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  USE_SWC = "true"
  VITE_API_BASE = "/.netlify/functions/api"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  functionsPort = 9999

[context.production]
  environment = { NODE_ENV = "production" }
