[build]
  base = "frontend"
  publish = "dist"
  command = """
    cd ../.netlify/functions && npm install && cd ../../frontend && \
    yarn install && CI=false yarn build
  """
  functions = "../.netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  USE_SWC = "true"
  VITE_API_BASE = "/.netlify/functions/api"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/**"]

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  functionsPort = 9999

[context.production]
  environment = { NODE_ENV = "production" }
